system:
  debug: true
  update-checking:
    enabled: true
    channel: 'bukkit'
    time: 'dev'
slots:
  track-statistics: true
  allow-diagonal-winnings: false
  enable-protection: true
chat:
  use-prefix: true
  prefix: '&c&o[Casino]&r'
  color: '&a'
